language: python
python:
  - 2.7
 
  
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE USER adrian WITH PASSWORD 'andela';" -U postgres
  - psql -c "CREATE DATABASE dev_db;" -U postgres
  - psql -c "CREATE USER adrian WITH PASSWORD 'andela';" -U postgres

install:
  - pip install -r requirements.txt
  - pip install coveralls
 

# command to run tests
script:
  - nose2 --with-cov --coverage tests    


after_success:
  - coveralls
