language: python
python:
  - 2.7
 
  
services:
  - postgresql

before_script:
  - createdb test_db 
  - createdb dev_db 


install:
  - pip install -r requirements.txt
  - pip install coveralls
 

# command to run tests
script:
  - nose2 --with-cov --coverage tests    


after_success:
  - coveralls
